# Generated by Django 4.1 on 2022-08-13 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HousePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField(max_length=255)),
                ('total_area', models.FloatField(default=100.0)),
                ('rooms', models.IntegerField()),
                ('floors', models.IntegerField()),
                ('additions', models.CharField(max_length=255)),
                ('parking_place', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=1000)),
                ('picture', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField(max_length=255)),
                ('amount', models.IntegerField(default=0)),
            ],
        ),
    ]
