# Generated by Django 4.1 on 2022-08-15 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houseplan',
            name='additions',
            field=models.CharField(choices=[('balcony', 'balcony'), ('terrace', 'terrace'), ('garden', 'garden'), ('none', 'none')], default='none', max_length=255),
        ),
        migrations.AlterField(
            model_name='houseplan',
            name='parking_place',
            field=models.CharField(choices=[('garage', 'garage'), ('carport', 'carport'), ('none', 'none')], default='none', max_length=255),
        ),
    ]
