# Generated by Django 4.1 on 2022-08-07 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
