# Generated by Django 4.1 on 2022-08-09 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0002_defaultprices'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultprices',
            name='hundred',
            field=models.FloatField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='defaultprices',
            name='hundredfifty',
            field=models.FloatField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='defaultprices',
            name='twohundred',
            field=models.FloatField(default=0, max_length=255),
        ),
    ]
