# Generated by Django 4.1 on 2022-08-11 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0003_defaultprices_hundred_defaultprices_hundredfifty_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('localization', models.CharField(max_length=255)),
                ('total_area', models.CharField(max_length=255)),
                ('price', models.FloatField(max_length=255)),
                ('rooms', models.IntegerField(max_length=255)),
                ('floors', models.IntegerField(max_length=255)),
                ('typeOfTransaction', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('additions', models.CharField(max_length=255)),
                ('parking_place', models.CharField(max_length=255)),
                ('heating', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
    ]
