# Generated by Django 4.1 on 2022-08-15 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0003_houseplan_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='houseplan',
            name='title',
        ),
    ]
