# Generated by Django 4.1 on 2022-08-13 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0004_house'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DefaultPrices',
        ),
        migrations.AlterField(
            model_name='house',
            name='floors',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='house',
            name='rooms',
            field=models.IntegerField(),
        ),
    ]
