# Generated by Django 4.1 on 2022-08-13 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0005_delete_defaultprices_alter_house_floors_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HousePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('total_area', models.CharField(max_length=255)),
                ('price', models.FloatField(max_length=255)),
                ('rooms', models.IntegerField()),
                ('floors', models.IntegerField()),
                ('additions', models.CharField(max_length=255)),
                ('parking_place', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='House',
        ),
    ]
