# Generated by Django 4.1 on 2022-08-20 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0008_seller_delete_whylikethis'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inventory',
        ),
    ]
