# Generated by Django 4.1 on 2022-08-20 22:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('construction', '0010_userfavourites_delete_seller'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserFavourites',
            new_name='UserFavourite',
        ),
    ]
