# Generated by Django 4.1 on 2022-08-22 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0013_usersettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='telephone_number',
            field=models.CharField(max_length=255),
        ),
    ]
