# Generated by Django 4.1 on 2022-09-01 14:30

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0014_alter_usersettings_telephone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+41524204242', max_length=128, region=None),
        ),
        migrations.DeleteModel(
            name='UserItem',
        ),
    ]
