# Generated by Django 4.1 on 2022-09-01 14:33

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0015_usersettings_phone_delete_useritem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='phone',
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='telephone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+41524204242', max_length=128, region=None),
        ),
    ]
