# Generated by Django 4.1 on 2022-09-05 18:55

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0018_alter_usersettings_telephone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='telephone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True),
        ),
    ]
